// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using QL_MuaBanMayTinh.Data;

#nullable disable

namespace QL_MuaBanMayTinh.Migrations
{
    [DbContext(typeof(MayTinhContext))]
    partial class MayTinhContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.24")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("QL_MuaBanMayTinh.Data.DanhMucSanPham", b =>
                {
                    b.Property<string>("MaDM")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("TenDanhMuc")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MaDM");

                    b.ToTable("DanhMucSanPham", (string)null);
                });

            modelBuilder.Entity("QL_MuaBanMayTinh.Data.SanPham", b =>
                {
                    b.Property<string>("MaSP")
                        .HasColumnType("nvarchar(450)");

                    b.Property<decimal>("Gia")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("HinhAnh")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MoTa")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenSanPham")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.HasKey("MaSP");

                    b.ToTable("SanPham");
                });

            modelBuilder.Entity("QL_MuaBanMayTinh.Data.SanPhamThanhPhan", b =>
                {
                    b.Property<string>("MaSP")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("MaTP")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("SoLuong")
                        .HasColumnType("int");

                    b.HasKey("MaSP", "MaTP");

                    b.HasIndex("MaTP");

                    b.ToTable("SanPhamThanhPhan", (string)null);
                });

            modelBuilder.Entity("QL_MuaBanMayTinh.Data.ThanhPhan", b =>
                {
                    b.Property<string>("MaTP")
                        .HasColumnType("nvarchar(450)");

                    b.Property<decimal>("GiaTP")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("MaDM")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("SLTonKho")
                        .HasColumnType("int");

                    b.Property<string>("SoSeri")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenTP")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MaTP");

                    b.HasIndex("MaDM");

                    b.ToTable("ThanhPhan", (string)null);
                });

            modelBuilder.Entity("QL_MuaBanMayTinh.Data.SanPhamThanhPhan", b =>
                {
                    b.HasOne("QL_MuaBanMayTinh.Data.SanPham", "SanPham")
                        .WithMany("SanPhamThanhPhans")
                        .HasForeignKey("MaSP")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_SPTP_SP");

                    b.HasOne("QL_MuaBanMayTinh.Data.ThanhPhan", "ThanhPhan")
                        .WithMany("SanPhamThanhPhans")
                        .HasForeignKey("MaTP")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_SPTP_TP");

                    b.Navigation("SanPham");

                    b.Navigation("ThanhPhan");
                });

            modelBuilder.Entity("QL_MuaBanMayTinh.Data.ThanhPhan", b =>
                {
                    b.HasOne("QL_MuaBanMayTinh.Data.DanhMucSanPham", "DanhMucSanPham")
                        .WithMany("ThanhPhans")
                        .HasForeignKey("MaDM")
                        .HasConstraintName("FK_TP_DMSP");

                    b.Navigation("DanhMucSanPham");
                });

            modelBuilder.Entity("QL_MuaBanMayTinh.Data.DanhMucSanPham", b =>
                {
                    b.Navigation("ThanhPhans");
                });

            modelBuilder.Entity("QL_MuaBanMayTinh.Data.SanPham", b =>
                {
                    b.Navigation("SanPhamThanhPhans");
                });

            modelBuilder.Entity("QL_MuaBanMayTinh.Data.ThanhPhan", b =>
                {
                    b.Navigation("SanPhamThanhPhans");
                });
#pragma warning restore 612, 618
        }
    }
}
